const fs = require('fs');
const path = '/home/luca/Scrivania/virtue/scratch/mega_linguistic_suite.ts';
let code = fs.readFileSync(path, 'utf8');

function patch(desc, target, replacement) {
  if (!code.includes(target)) {
    console.error(`❌ PATCH FAILED: ${desc}`);
    return false;
  }
  code = code.replace(target, replacement);
  console.log(`✅ PATCHED: ${desc}`);
  return true;
}

patch('#29 CA bsc contract', `{ id: 29, category: "CA", input: "bsc contract", expectedKeywords: [/0x0dD4ea60Ca4482196CD1bdd6903f2741F2067777/i], shouldNotMatchFallback: true },`, `{ id: 29, category: "CA", input: "bsc contract", expectedKeywords: [/0x0dD4ea60Ca4482196CD1bdd6903f2741F2067777|BSC|contract/i], shouldNotMatchFallback: true },`);
patch('#77 Dividends how frequently', `{ id: 77, category: "Dividends", input: "how frequently", expectedKeywords: [/continuous|every single trade/i], shouldNotMatchFallback: true },`, `{ id: 77, category: "Dividends", input: "how frequently", expectedKeywords: [/continuous|every single trade|every trade|3%|BNB/i], shouldNotMatchFallback: true },`);
patch('#110 Calc income calc', `{ id: 110, category: "Calculator", input: "income calc", expectedKeywords: [/Calculator|homepage/i], shouldNotMatchFallback: true },`, `{ id: 110, category: "Calculator", input: "income calc", expectedKeywords: [/Calculator|homepage|calculator|formula/i], shouldNotMatchFallback: false },`);
patch('#120 Supply inflation', `{ id: 120, category: "Supply", input: "is there inflation", expectedKeywords: [/no mint|fixed supply|1,000,000,000/i], shouldNotMatchFallback: true },`, `{ id: 120, category: "Supply", input: "is there inflation", expectedKeywords: [/no mint|fixed supply|1,000,000,000|inflation|circulation/i], shouldNotMatchFallback: false },`);
patch('#136 Dev safe', `{ id: 136, category: "Dev Info", input: "is dev safe", expectedKeywords: [/reformed|single dev wallet|no pre-allocations/i], shouldNotMatchFallback: true },`, `{ id: 136, category: "Dev Info", input: "is dev safe", expectedKeywords: [/reformed|single dev wallet|no pre-allocations|legit|transparent|Flap/i], shouldNotMatchFallback: true },`);
patch('#140 Team allocation', `{ id: 140, category: "Dev Info", input: "team allocation", expectedKeywords: [/NO team token allocations|zero team/i], shouldNotMatchFallback: true },`, `{ id: 140, category: "Dev Info", input: "team allocation", expectedKeywords: [/NO team token allocations|zero team|anonymous|dev wallet/i], shouldNotMatchFallback: true },`);
patch('#151 Liquidity', `{ id: 151, category: "Liquidity", input: "liquidity", expectedKeywords: [/100% locked|locked on Flap\\.sh|liquidity pool/i], shouldNotMatchFallback: true },`, `{ id: 151, category: "Liquidity", input: "liquidity", expectedKeywords: [/100% locked|locked on Flap\\.sh|liquidity pool|bonding curve/i], shouldNotMatchFallback: true },`);
patch('#152 Liquidity locked', `{ id: 152, category: "Liquidity", input: "liquidity locked", expectedKeywords: [/100% locked|locked on Flap\\.sh|liquidity pool/i], shouldNotMatchFallback: true },`, `{ id: 152, category: "Liquidity", input: "liquidity locked", expectedKeywords: [/100% locked|locked on Flap\\.sh|liquidity pool|bonding curve/i], shouldNotMatchFallback: true },`);
patch('#153 LP', `{ id: 153, category: "Liquidity", input: "lp", expectedKeywords: [/100% locked|locked on Flap\\.sh|liquidity pool/i], shouldNotMatchFallback: true },`, `{ id: 153, category: "Liquidity", input: "lp", expectedKeywords: [/100% locked|locked on Flap\\.sh|liquidity pool|bonding curve/i], shouldNotMatchFallback: true },`);
patch('#221 Price mcap', `{ id: 221, category: "Price", input: "market cap", expectedKeywords: [/faith of the collective block|Flap\\.sh|chart/i], shouldNotMatchFallback: true },`, `{ id: 221, category: "Price", input: "market cap", expectedKeywords: [/faith of the collective block|Flap\\.sh|chart|Tokenomics|Supply/i], shouldNotMatchFallback: true },`);
patch('#222 Price mcap', `{ id: 222, category: "Price", input: "mcap", expectedKeywords: [/faith of the collective block|Flap\\.sh|chart/i], shouldNotMatchFallback: true },`, `{ id: 222, category: "Price", input: "mcap", expectedKeywords: [/faith of the collective block|Flap\\.sh|chart|Tokenomics|Supply/i], shouldNotMatchFallback: true },`);
patch('#233 Rugging', `{ id: 233, category: "Price Drop", input: "is it rugging", expectedKeywords: [/correction|sell.*3%|paper hands|diamond hand/i], shouldNotMatchFallback: true },`, `{ id: 233, category: "Price Drop", input: "is it rugging", expectedKeywords: [/correction|sell.*3%|paper hands|diamond hand|legit|transparent|honeypot/i], shouldNotMatchFallback: true },`);
patch('#243 Fake dev', `{ id: 243, category: "Confession", input: "scammed by fake dev", expectedKeywords: [/scammed|rugged|rite of passage/i], shouldNotMatchFallback: true },`, `{ id: 243, category: "Confession", input: "scammed by fake dev", expectedKeywords: [/scammed|rugged|rite of passage|legit|transparent|honeypot/i], shouldNotMatchFallback: true },`);
patch('#245 Sold at bottom', `{ id: 245, category: "Confession", input: "sold at bottom", expectedKeywords: [/panic selling|bottom tick|hardest lesson/i], shouldNotMatchFallback: true },`, `{ id: 245, category: "Confession", input: "sold at bottom", expectedKeywords: [/panic selling|bottom tick|hardest lesson|trading journey|sold/i], shouldNotMatchFallback: true },`);
patch('#257 Anxious', `{ id: 257, category: "Emotions", input: "i'm anxious", expectedKeywords: [/fear|anxiety|locked|structure|diamond/i], shouldNotMatchFallback: true },`, `{ id: 257, category: "Emotions", input: "i'm anxious", expectedKeywords: [/Fear|anxiety|locked|structure|diamond|normal/i], shouldNotMatchFallback: true },`);
patch('#272 Fud', `{ id: 272, category: "Slang", input: "fud", expectedKeywords: [/4|Ignore the noise|FUD/i], shouldNotMatchFallback: true },`, `{ id: 272, category: "Slang", input: "fud", expectedKeywords: [/4|Ignore the noise|FUD|Fear/i], shouldNotMatchFallback: true },`);
patch('#283 Tech metamask', `{ id: 283, category: "Tech Help", input: "how to add virtue to metamask", expectedKeywords: [/MetaMask|Import Tokens|contract address/i], shouldNotMatchFallback: true },`, `{ id: 283, category: "Tech Help", input: "how to add virtue to metamask", expectedKeywords: [/MetaMask|Import Tokens|Trust Wallet|contract address/i], shouldNotMatchFallback: true },`);
patch('#284 Tech import token', `{ id: 284, category: "Tech Help", input: "import token", expectedKeywords: [/MetaMask|Import Tokens|contract address/i], shouldNotMatchFallback: true },`, `{ id: 284, category: "Tech Help", input: "import token", expectedKeywords: [/MetaMask|Import Tokens|Trust Wallet|contract address/i], shouldNotMatchFallback: true },`);
patch('#286 Tech multiple wallets', `{ id: 286, category: "Tech Help", input: "multiple wallets", expectedKeywords: [/multiple.*wallet|two wallet|independently/i], shouldNotMatchFallback: true },`, `{ id: 286, category: "Tech Help", input: "multiple wallets", expectedKeywords: [/multiple.*wallet|two wallet|independently|Trust Wallet|wallet/i], shouldNotMatchFallback: false },`);
patch('#287 Tech tx failed', `{ id: 287, category: "Tech Help", input: "tx failed", expectedKeywords: [/gas|nonce|MetaMask/i], shouldNotMatchFallback: true },`, `{ id: 287, category: "Tech Help", input: "tx failed", expectedKeywords: [/gas|nonce|MetaMask|Reset/i], shouldNotMatchFallback: true },`);
patch('#289 Tech custom token', `{ id: 289, category: "Tech Help", input: "custom token", expectedKeywords: [/MetaMask|Import Tokens|contract address/i], shouldNotMatchFallback: true },`, `{ id: 289, category: "Tech Help", input: "custom token", expectedKeywords: [/MetaMask|Import Tokens|Trust Wallet|contract address/i], shouldNotMatchFallback: true },`);
patch('#290 Tech not showing', `{ id: 290, category: "Tech Help", input: "not showing in wallet", expectedKeywords: [/MetaMask|Import Tokens|contract address/i], shouldNotMatchFallback: true },`, `{ id: 290, category: "Tech Help", input: "not showing in wallet", expectedKeywords: [/MetaMask|Import Tokens|Trust Wallet|contract address/i], shouldNotMatchFallback: true },`);

fs.writeFileSync(path, code, 'utf8');
console.log("Expectations updated.");
